package sim

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/tollwing/tollwing/pkg/classifier"
	"github.com/tollwing/tollwing/test/sim/scenario"
)

// TestCoverage is the suite's coverage GATE + report — the "living artifact"
// maintenance model from DEC-008. It asserts every priceable traffic type is
// exercised by at least one scenario, so adding a TrafficType without a scenario
// fails CI ("every feature/PR adds a scenario").
// With -update it regenerates docs/testing/coverage.md (the claim→scenario→$
// matrix that lets anyone see, at a glance, what the suite proves).
func TestCoverage(t *testing.T) {
	type row struct{ scenario, edge, cost string }

	covered := map[string][]row{}
	paths, _ := filepath.Glob("scenarios/*.yaml")
	if len(paths) == 0 {
		t.Fatal("no scenarios found")
	}
	for _, p := range paths {
		s, err := scenario.Load(p)
		if err != nil {
			t.Fatalf("load %s: %v", p, err)
		}
		for _, e := range s.Expect.Edges {
			cost := "—"
			if e.CostUSD != nil {
				cost = fmt.Sprintf("$%.4f", *e.CostUSD)
			}
			covered[e.Type] = append(covered[e.Type], row{s.Name, e.From + "→" + e.To, cost})
		}
	}

	// Every emittable traffic type must have a scenario, except documented exemptions.
	exempt := map[classifier.TrafficType]string{
		classifier.Unknown: "emitted only when zones are unresolved; covered by pkg/classifier unit tests",
	}
	var missing []string
	for tt := classifier.SameZone; tt < classifier.NumTrafficTypes; tt++ {
		if _, ok := exempt[tt]; ok {
			continue
		}
		if len(covered[tt.String()]) == 0 {
			missing = append(missing, tt.String())
		}
	}
	if len(missing) > 0 {
		t.Errorf("traffic types with NO scenario (add one — every classifier type must be proven): %v", missing)
	}

	// Build the coverage report.
	var b bytes.Buffer
	fmt.Fprintf(&b, "# Tollwing simulation suite — coverage\n\n")
	fmt.Fprintf(&b, "<!-- generated by `go test ./test/sim/ -run Coverage -update`; do not edit by hand -->\n\n")
	fmt.Fprintf(&b, "Run it: `make sim` (L0+L1), `make sim-l2a`, `make sim-l2b`. See DEC-008.\n\n")
	fmt.Fprintf(&b, "## Tiers\n\n| Tier | Entrypoint | Proves |\n|---|---|---|\n")
	fmt.Fprintf(&b, "| L0 | `make sim` | classification + cost + transitive attribution + reconciliation, exact-$ (pure Go, runs anywhere) |\n")
	fmt.Fprintf(&b, "| L1 | `make sim` | real ClickHouse + real tollwing-server, exact-$ on the live API |\n")
	fmt.Fprintf(&b, "| L2a | `make sim-l2a` | real kind cluster + real demo apps + the injector, exact-$ |\n")
	fmt.Fprintf(&b, "| L2b | `make sim-l2b` | the real eBPF agent captures + classifies real cross-AZ bytes (Lima BTF VM) |\n\n")
	fmt.Fprintf(&b, "## Traffic-type coverage (L0 scenarios)\n\n| Traffic type | Scenario | Edge | Expected |\n|---|---|---|---|\n")
	for tt := classifier.SameZone; tt < classifier.NumTrafficTypes; tt++ {
		name := tt.String()
		if rows := covered[name]; len(rows) > 0 {
			for _, r := range rows {
				fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", name, r.scenario, r.edge, r.cost)
			}
		} else if reason, ok := exempt[tt]; ok {
			fmt.Fprintf(&b, "| `%s` | _(exempt)_ | — | %s |\n", name, reason)
		}
	}
	report := b.String()
	t.Logf("coverage matrix:\n%s", report)

	if *update {
		out := filepath.Join("..", "..", "docs", "testing", "coverage.md")
		if err := os.WriteFile(out, []byte(report), 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("wrote %s", out)
	}
}
